INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'gee joon 6', 0, 15, 3, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'gee joon 3', 0, 15, 3, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'teen', 15, 14, 12, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'teen', 15, 14, 12, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'day', 14, 13, 2, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'day', 14, 13, 2, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'high eight', 13, 12, 8, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'high eight', 13, 12, 8, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'harmony four', 12, 11, 4, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'harmony four', 12, 11, 4, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'high ten', 11, 10, 10, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'high ten', 11, 10, 10, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'long six', 10, 9, 6, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'long six', 10, 9, 6, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'low four', 9, 8, 4, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'low four', 9, 8, 4, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'eleven', 8, 7, 11, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'eleven', 8, 7, 11, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'low ten', 7, 6, 10, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'low ten', 7, 6, 10, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'high seven', 6, 5, 7, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'high seven', 6, 5, 7, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'low six', 5, 4, 6, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'low six', 5, 4, 6, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'mixed nine', 4, 3, 9, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'mixed nine', 4, 3, 9, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'mixed eight', 3, 2, 8, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'mixed eight', 3, 2, 8, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'mixed seven', 2, 1, 7, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'mixed seven', 2, 1, 7, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'mixed five', 1, 0, 5, 0, 0 );
INSERT INTO paigow_tile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'mixed five', 1, 0, 5, 0, 0 );
COMMIT;

