INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'gee joon 6', 0, 15, 3, 500, 500 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'gee joon 3', 0, 15, 3, 200, 0 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'teen', 15, 14, 12, 0, 250 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'teen', 15, 14, 12, 0, 250 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'day', 14, 13, 2, 500, 750 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'day', 14, 13, 2, 500, 750 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'high eight', 13, 12, 8, 200, 500  );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'high eight', 13, 12, 8, 200, 500 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'harmony four', 12, 11, 4, 100, 750 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'harmony four', 12, 11, 4, 100, 750 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'high ten', 11, 10, 10, 100, 500 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'high ten', 11, 10, 10, 100, 500 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'long six', 10, 9, 6, 300, 750 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'long six', 10, 9, 6, 300, 750 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'low four', 9, 8, 4, 400, 750 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'low four', 9, 8, 4, 400, 750 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'eleven', 8, 7, 11, 300, 500 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'eleven', 8, 7, 11, 300, 500 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'low ten', 7, 6, 10, 200, 750 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'low ten', 7, 6, 10, 200, 750 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'high seven', 6, 5, 7, 500, 0 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'high seven', 6, 5, 7, 500, 0 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'low six', 5, 4, 6, 300, 0 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'low six', 5, 4, 6, 300, 0 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'mixed nine', 4, 3, 9, 100, 0 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'mixed nine', 4, 3, 9, 400, 0 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'mixed eight', 3, 2, 8, 100, 250 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'mixed eight', 3, 2, 8, 500, 250 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'mixed seven', 2, 1, 7, 200, 250 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'mixed seven', 2, 1, 7, 400, 250 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'mixed five', 1, 0, 5, 300, 250 );
INSERT INTO paigow_pgtile (name, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'mixed five', 1, 0, 5, 400, 500 );
