INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'gee joon', 'P', 0, 15, 3, 500, 500 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'gee joon', 'p', 0, 15, 3, 200, 0 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'teen', 'A', 15, 14, 12, 0, 250 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'teen', 'a', 15, 14, 12, 0, 250 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'day', 'B', 14, 13, 2, 500, 750 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'day', 'b', 14, 13, 2, 500, 750 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'high eight', 'C', 13, 12, 8, 200, 500  );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'high eight', 'c', 13, 12, 8, 200, 500 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'harmony four', 'D', 12, 11, 4, 100, 750 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'harmony four', 'd', 12, 11, 4, 100, 750 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'high ten', 'E', 11, 10, 10, 100, 500 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'high ten', 'e', 11, 10, 10, 100, 500 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'long six', 'F', 10, 9, 6, 300, 750 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'long six', 'f', 10, 9, 6, 300, 750 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'low four', 'G', 9, 8, 4, 400, 750 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'low four', 'g', 9, 8, 4, 400, 750 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'eleven', 'H', 8, 7, 11, 300, 500 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'eleven', 'h', 8, 7, 11, 300, 500 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'low ten', 'I', 7, 6, 10, 200, 750 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'low ten', 'i', 7, 6, 10, 200, 750 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'high seven', 'J', 6, 5, 7, 500, 0 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'high seven', 'j', 6, 5, 7, 500, 0 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'low six', 'K', 5, 4, 6, 300, 0 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'low six', 'k', 5, 4, 6, 300, 0 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'mixed nine', 'L', 4, 3, 9, 100, 0 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'mixed nine', 'l', 4, 3, 9, 400, 0 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'mixed eight', 'M', 3, 2, 8, 100, 250 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'mixed eight', 'm', 3, 2, 8, 500, 250 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'mixed seven', 'N', 2, 1, 7, 200, 250 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'mixed seven', 'n', 2, 1, 7, 400, 250 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'mixed five', 'O', 1, 0, 5, 300, 250 );
INSERT INTO paigow_pgtile (name, tile_char, tile_rank, pair_rank, tile_value, sprite_left, sprite_top) VALUES ( 'mixed five', 'o', 1, 0, 5, 400, 500 );
