INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'gee joon 6', 0, 15, 3 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'gee joon 3', 0, 15, 3 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'teen', 15, 14, 12 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'teen', 15, 14, 12 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'day', 14, 13, 2 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'day', 14, 13, 2 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'high eight', 13, 12, 8 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'high eight', 13, 12, 8 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'harmony four', 12, 11, 4 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'harmony four', 12, 11, 4 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'high ten', 11, 10, 10 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'high ten', 11, 10, 10 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'long six', 10, 9, 6 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'long six', 10, 9, 6 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'low four', 9, 8, 4 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'low four', 9, 8, 4 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'eleven', 8, 7, 11 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'eleven', 8, 7, 11 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'low ten', 7, 6, 10 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'low ten', 7, 6, 10 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'high seven', 6, 5, 7 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'high seven', 6, 5, 7 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'low six', 5, 4, 6 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'low six', 5, 4, 6 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'mixed nine', 4, 3, 9 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'mixed nine', 4, 3, 9 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'mixed eight', 3, 2, 8 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'mixed eight', 3, 2, 8 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'mixed seven', 2, 1, 7 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'mixed seven', 2, 1, 7 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'mixed five', 1, 0, 5 )
INSERT INTO paigow_tile (tile_name, tile_rank, pair_rank, tile_value) VALUES ( 'mixed five', 1, 0, 5 )
COMMIT
